"""Internal flags for ONNX export."""

from __future__ import annotations

import functools
<<<<<<< HEAD
from typing import Callable, TypeVar
from typing_extensions import ParamSpec
=======
from typing import Any, Callable, cast, TypeVar
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))


_is_onnx_exporting = False

<<<<<<< HEAD
# Use ParamSpec to preserve parameter types instead of erasing to Any
_P = ParamSpec("_P")
_R = TypeVar("_R")


def set_onnx_exporting_flag(func: Callable[_P, _R]) -> Callable[_P, _R]:
    @functools.wraps(func)
    def wrapper(*args: _P.args, **kwargs: _P.kwargs) -> _R:
=======
TCallable = TypeVar("TCallable", bound=Callable[..., Any])


def set_onnx_exporting_flag(func: TCallable) -> TCallable:
    @functools.wraps(func)
    def wrapper(*args: Any, **kwargs: Any) -> Any:
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
        global _is_onnx_exporting
        _is_onnx_exporting = True
        try:
            return func(*args, **kwargs)
        finally:
            # Ensure it resets even if an exception occurs
            _is_onnx_exporting = False

<<<<<<< HEAD
    return wrapper
=======
    return cast(TCallable, wrapper)
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
