def define_targets(rules):
    rules.py_library(
        name = "autograd",
        srcs = rules.glob(["*.py"]),
        data = rules.glob([
            "*.yaml",
            "templates/*",
        ]),
        visibility = ["//:__subpackages__"],
        deps = [
            rules.requirement("PyYAML"),
            "//torchgen",
        ],
    )
<<<<<<< HEAD

    rules.filegroup(
        name = "deprecated_yaml",
        srcs = ["deprecated.yaml"],
        visibility = ["//:__subpackages__"],
    )
=======
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
