// !!! This is a file automatically generated by hipify!!!
#include <gtest/gtest.h>

#include <c10/core/Device.h>
#include <c10/core/DeviceType.h>
#include <c10/hip/HIPException.h>
#if !defined(USE_ROCM) && !defined(__HIP_PLATFORM_AMD__)
#include <c10/cuda/driver_api.h>
#endif
#include <c10/hip/impl/HIPGuardImpl.h>
#include <c10/hip/impl/HIPTest.h>

using namespace c10::cuda::impl;

TEST(CUDATest, SmokeTest) {
  c10_cuda_test();
}

// Regression: the device-guard restore path is noexcept, but internally
// MaybeSetDevice() -> SetDevice() can throw -- via TORCH_CHECK(device >= 0) on
// the pre-CUDA-12 / HIP path (a pure host check), or via
// C10_CUDA_CHECK(hipGetDevice) on a device carrying a sticky error. A leaked
// throw from a noexcept method calls std::terminate. A negative device index
// deterministically hits the TORCH_CHECK throw where MaybeSetDevice routes to
// SetDevice, so uncheckedSetDevice must swallow it (warn) instead of
// terminating -- if it regresses, this process aborts. On the CUDA-12 branch
// MaybeSetDevice short-circuits for an invalid index, so this is a benign
// no-op there.
TEST(CUDAGuardImplTest, UncheckedSetDeviceSwallowsErrorAndDoesNotTerminate) {
  CUDAGuardImpl impl;
  EXPECT_NO_THROW(
      impl.uncheckedSetDevice(c10::Device(c10::DeviceType::CUDA, -1)));
}

#if !defined(USE_ROCM) && !defined(__HIP_PLATFORM_AMD__) && \
    defined(TORCH_HIP_VERSION) && (TORCH_HIP_VERSION >= 12090)
TEST(CUDAErrorTest, IncludesDriverErrorLog) {
  int device_count = 0;
  if (hipGetDeviceCount(&device_count) != hipSuccess || device_count == 0) {
    hipGetLastError();
    GTEST_SKIP() << "No CUDA device is available";
  }

  auto* log_api = c10::cuda::DriverAPI::get();
  if (!log_api->cuLogsRegisterCallback_) {
    GTEST_SKIP() << "The CUDA driver log APIs are unavailable";
  }

  int device = 0;
  ASSERT_EQ(hipGetDevice(&device), hipSuccess);

  hipGraph_t graph = nullptr;
  ASSERT_EQ(hipGraphCreate(&graph, 0), hipSuccess);

  cudaMemAllocNodeParams params{};
  params.poolProps.allocType = hipMemAllocationTypePinned;
  params.poolProps.location.type = hipMemLocationTypeDevice;
  params.poolProps.location.id = device;
  params.bytesize = 4;
  hipGraphNode_t node = nullptr;
  ASSERT_EQ(
      hipGraphAddMemAllocNode(&node, graph, nullptr, 0, &params), hipSuccess);

  bool threw = false;
  hipGraphExec_t graph_exec = nullptr;
  try {
    C10_CUDA_CHECK(hipGraphInstantiateWithFlags(
        &graph_exec, graph, hipGraphInstantiateFlagDeviceLaunch));
  } catch (const c10::AcceleratorError& error) {
    threw = true;
    EXPECT_NE(
        std::string(error.what_without_backtrace())
            .find(
                "The CUDA driver logged these messages, which may provide useful details:"),
        std::string::npos);
    EXPECT_NE(
        std::string(error.what_without_backtrace())
            .find(
                "Device-launched graphs and conditional nodes do not support MEM_ALLOC nodes"),
        std::string::npos);
  }

  EXPECT_TRUE(threw);
  if (graph_exec) {
    EXPECT_EQ(hipGraphExecDestroy(graph_exec), hipSuccess);
  }
  EXPECT_EQ(hipGraphDestroy(graph), hipSuccess);
}
#endif
