#pragma once

<<<<<<< HEAD
#include <torch/nativert/executor/memory/LayoutPlannerSettings.h>
=======
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
#include <cstdint>
#include <string>

namespace torch::nativert {

struct ExecutorConfig {
  bool validateInputs = false;
  bool debugNan = false;
<<<<<<< HEAD
  bool enableStaticCPUKernels = true;
  bool runConstFolding = false;
  bool doExecutionFrameCleanup = true;
  bool tryFreeUnmanagedValuesAfterUse = true;
=======
  bool enableStaticCPUKernels = false;
  bool enableStaticMemoryPlanning = false;
  bool runConstFolding = false;
  bool doExecutionFrameCleanup = true;
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
  // allows up to max number of concurrent threads.
  int64_t maxNumConcurrentThreads = 8;
  // allows up to max number of parallel ops.
  int64_t maxParallelOps = 1;
  int64_t minNumExecutionFrames = 1;
  int64_t executionFramePoolCleanupIntervalSec = 600;
<<<<<<< HEAD
  LayoutPlannerSettings layoutPlannerSettings;
=======
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
  std::string modelName = "unknown";
};

} // namespace torch::nativert
