#pragma once

#include <cstdint>

namespace torch::nativert {

enum class OpKernelKind : uint8_t {
  kPrimKernel,
  kStaticDispatchKernel,
  kInterpreterFallbackKernel,
<<<<<<< HEAD
  // static dispatch kernels that don't reuse
  // out TensorImpl
  kNativeStaticDispatchKernel,
  kTritonKernel,
=======
  // static dispatch kernels that don't re-use
  // out TensorImpl
  kNativeStaticDispatchKernel,
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
};

} // namespace torch::nativert
