# This is a wrapper of the upstream `./upstream/FindCUDA.cmake` that
# automatically includes `./upstream/CMakeInitializeConfigs.cmake` before
# `./upstream/FindCUDA.cmake`. The `CMakeInitializeConfigs.cmake`, which is
# absent in old CMake versions, creates some necessary variables for the later
# to run.
# See ./README.md for details.

set(UPSTREAM_FIND_CUDA_DIR "${CMAKE_CURRENT_LIST_DIR}/upstream/")

<<<<<<< HEAD
=======
include("${UPSTREAM_FIND_CUDA_DIR}/CMakeInitializeConfigs.cmake")
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
include("${UPSTREAM_FIND_CUDA_DIR}/FindCUDA.cmake")
