from model import get_custom_op_library_path

import torch


torch.ops.load_library(get_custom_op_library_path())


<<<<<<< HEAD
@torch.library.register_fake("custom::sin")
=======
@torch.library.impl_abstract("custom::sin")
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
def sin_abstract(x):
    return torch.empty_like(x)
