from model import get_custom_op_library_path

import torch


torch.ops.load_library(get_custom_op_library_path())


<<<<<<< HEAD
@torch.library.register_fake("custom::nonzero")
=======
@torch.library.impl_abstract("custom::nonzero")
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
def nonzero_abstract(x):
    n = x.dim()
    ctx = torch.library.get_ctx()
    nnz = ctx.create_unbacked_symint()
    shape = [nnz, n]
    return x.new_empty(shape, dtype=torch.long)
