from model import get_custom_op_library_path

import torch


torch.ops.load_library(get_custom_op_library_path())


# NB: The impl_abstract_pystub for cos actually
# specifies it should live in the my_custom_ops2 module.
<<<<<<< HEAD
@torch.library.register_fake("custom::cos")
=======
@torch.library.impl_abstract("custom::cos")
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
def cos_abstract(x):
    return torch.empty_like(x)


# NB: There is no impl_abstract_pystub for tan
<<<<<<< HEAD
@torch.library.register_fake("custom::tan")
=======
@torch.library.impl_abstract("custom::tan")
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
def tan_abstract(x):
    return torch.empty_like(x)
