# Whether to disable showing progress on compilation passes
<<<<<<< HEAD
# Need to add a new config otherwise will get a circular import if dynamo config is imported here
=======
# Need to add a new config otherwise wil get a circular import if dynamo config is imported here
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
disable_progress = True

# If True this also shows the node names in each pass, for small models this is great but larger models it's quite noisy
verbose_progress = False
