# mypy: allow-untyped-defs
# Defined in torch/csrc/cuda/shared/roctx.cpp (ROCm builds only)
def rangePushA(message: str) -> int: ...
def rangePop() -> int: ...
def rangeStartA(message: str) -> int: ...
def rangeEnd(range_id: int) -> None: ...
def markA(message: str) -> None: ...
def deviceRangeStart(message: str, stream: int = 0) -> object: ...
def deviceRangeEnd(range_handle: object, stream: int = 0) -> None: ...
