#pragma once

#include <ATen/core/function_schema.h>
#include <torch/nativert/executor/OpKernelKind.h>

namespace torch::nativert {

struct InputOutputIdxPair {
  size_t input_idx;
  size_t output_idx;
};

using AliasingSpec = std::vector<InputOutputIdxPair>;

class FunctionSchema {
 public:
  explicit FunctionSchema(
      const c10::FunctionSchema& schema,
      AliasingSpec&& aliasing_spec = {},
<<<<<<< HEAD
      OpKernelKind kernel_kind = OpKernelKind::kInterpreterFallbackKernel)
=======
      torch::nativert::OpKernelKind kernel_kind =
          torch::nativert::OpKernelKind::kInterpreterFallbackKernel)
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
      : aliasing_spec_(std::move(aliasing_spec)),
        kernel_kind_(kernel_kind),
        c10_fn_schema_(schema) {}

  c10::FunctionSchema& base_schema() {
    return c10_fn_schema_;
  }

  const c10::FunctionSchema& base_schema() const {
    return c10_fn_schema_;
  }

  bool alias(size_t input_idx, size_t output_idx) const;

<<<<<<< HEAD
  C10_ALWAYS_INLINE OpKernelKind kernel_kind() const {
=======
  C10_ALWAYS_INLINE torch::nativert::OpKernelKind kernel_kind() const {
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
    return kernel_kind_;
  }

 private:
  AliasingSpec aliasing_spec_;
<<<<<<< HEAD
  OpKernelKind kernel_kind_;
=======
  torch::nativert::OpKernelKind kernel_kind_;
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
  c10::FunctionSchema c10_fn_schema_;
};

} // namespace torch::nativert
