<<<<<<< HEAD
from .type_promotion import InsertTypePromotion


__all__ = [
    "InsertTypePromotion",
=======
from .decomp import Decompose
from .functionalization import Functionalize, RemoveInputMutation
from .modularization import Modularize
from .readability import RestoreParameterAndBufferNames
from .type_promotion import InsertTypePromotion
from .virtualization import MovePlaceholderToFront, ReplaceGetAttrWithPlaceholder


__all__ = [
    "Decompose",
    "InsertTypePromotion",
    "Functionalize",
    "Modularize",
    "MovePlaceholderToFront",
    "RemoveInputMutation",
    "RestoreParameterAndBufferNames",
    "ReplaceGetAttrWithPlaceholder",
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))
]
