#pragma once

#include <torch/nativert/graph/Graph.h>

namespace torch::nativert {

<<<<<<< HEAD
void selectScalarOverload(Graph* graph);

std::string selectScalarOverloadName(const Node& node);
=======
void selectScalarOverload(torch::nativert::Graph* graph);

std::string selectScalarOverloadName(const torch::nativert::Node& node);
>>>>>>> 245bf6edbc ([AUTOGENERATED] [release/2.8] skip convolution tests on Navi4x (#2675))

} // namespace torch::nativert
