name: ROCm Nightly Runner Smoke Test

on:
  push:
    branches:
      - rocm-nightly-gha
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: read-all

jobs:
  runner-smoke-test:
    name: ${{ matrix.target.name }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: Smoke Test on MI325
            runner: linux-pytorch-mi325-1
          - name: Smoke Test on MI250
            runner: linux-pytorch-mi250-1
    runs-on: ${{ matrix.target.runner }}
    timeout-minutes: 10
    steps:
      - name: Run rocm-smi
        shell: bash
        run: |
          command -v rocm-smi
          rocm-smi
